services:
  redis_standalone:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./cache:/data
      # - /dev/volumes/nestjs-remix/dev/sessions/:/data

